{% set name = "wakatime" %}
{% set version = "14.0.0" %}
{% set sha256 = "4eeb4778a9910ea10bcc4819ba5a9cc6862b0b4e0f1d304401e2f48ea86bfb31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - wakatime = wakatime.__init__:execute

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wakatime

  commands:
    - wakatime --help

about:
  home: https://wakatime.com
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/wakatime/wakatime
  summary: Common interface to the WakaTime api.

extra:
  recipe-maintainers:
    - proinsias
