{% set name = "wakatime" %}
{% set version = "6.2.0" %}
{% set sha256 = "e8eaba0dd83621b2bd4d1e71b1775ec78f65823d07ae4b1f65fa085210418b78" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - wakatime = wakatime.__init__:execute

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wakatime

  commands:
    - wakatime --help

about:
  home: https://wakatime.com
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/wakatime/wakatime
  summary: 'Common interface to the WakaTime api.'

extra:
  recipe-maintainers:
    - proinsias
