{% set name = "wakatime" %}
{% set version = "14.0.1" %}
{% set sha256 = "a4dd92772292ad4832cd686d88e3fa433fbcf3e95328ab19528ae56ba7be87bf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - wakatime = wakatime.__init__:execute

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6

test:
  imports:
    - wakatime

about:
  home: https://wakatime.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/wakatime/wakatime
  summary: Common interface to the WakaTime api.

extra:
  recipe-maintainers:
    - proinsias
