travis:
  secure:
    BINSTAR_TOKEN: dhzuJwtnZpfc4CZ/x8NOjikgaHAnyEIhLu7mQuCY3t/tV1evdGT+BKP1xl2hl5Cz5K2WOsNNuDMaAl9wqF9WAqpdPDCt9LAUxUjRPhRbdc+2v/+JeOTBYLOkwOp5aOY4Hd4MdwoD5om6FazzVMJqoMalZm+6PCYKj41Q117emWGNZGsPARhccaH5x0bAo0d/hWpui+8NRIDG/8pbt2yzb1STPp5UeApVAJCK4BIghArH2zpuA7KJ6pS6NwHv2nhoPqhwnG/n0vgwK3994qyw+IlKWDvOHik8deP++TIrL99ZeN/+SWkRUykk5A3COgf/cByqgfYKw1X1U+jZNy6DdRyjzudDoT0Ynf+TfZk7Lav0ZjBxm2pFH+yROZhwxVzBeFyl+S+i9A02y1f7PlXoe7wu9L8iOup6XLgWcUiueg6+35NlHB45UI+PqviXjgoJ39OX+d683QE4w3lpuu/PL+Si3UdThSSDKfKOL8I96rOk6zXSRqih6PsDZjpt55SpmF0MD+Uev1HByk6fV050obQCmyvfnffqi7JZydTSdI9Ee+aAo7v/mQ6VmWWEirz2KqRYMEOpCP0Qz6wd3wztWJKSTrrhdbzmE9rf93iGcdfu0SX3xX2KHG8s7cjvYcXJ1rv0ObOn7nTuiYsbjqvjeKxDpJBrQiGeRcG5y45imiM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
